// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Account
 */
export type Account = {
    /**
     * Blueprint
     */
    blueprint: string;
    /**
     * Blueprint Version
     */
    blueprint_version: number;
    brand?: BrandKit;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'clips' | 'story' | 'band' | 'avatar' | 'model';
    /**
     * Language
     */
    language: 'en' | 'es';
    /**
     * Monthly Budget Usd
     */
    monthly_budget_usd?: number;
    /**
     * Niche
     */
    niche: string;
    /**
     * Paired Account Id
     */
    paired_account_id?: string | null;
    /**
     * Persona Id
     */
    persona_id?: string | null;
    /**
     * Platforms
     */
    platforms: {
        [key in Platform]?: PlatformProfile;
    };
    posting?: PostingSchedule;
    publisher?: PublisherProfile | null;
    /**
     * Review Tier
     */
    review_tier?: 'review' | 'sample' | 'auto';
};

/**
 * AccountCreate
 */
export type AccountCreate = {
    /**
     * Blueprint
     */
    blueprint: string;
    /**
     * Handle
     */
    handle: string;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Language
     */
    language: 'en' | 'es';
    /**
     * Posting From Env
     */
    posting_from_env?: boolean;
};

/**
 * AccountEdit
 */
export type AccountEdit = {
    /**
     * Chat Id
     */
    chat_id?: number | null;
    /**
     * Clear Chat
     */
    clear_chat?: boolean;
    /**
     * Handles
     */
    handles?: {
        [key in Platform]?: string;
    };
    /**
     * Hashtags
     */
    hashtags?: Array<string> | null;
    /**
     * Review Tier
     */
    review_tier?: 'review' | 'sample' | 'auto' | null;
    /**
     * Slots
     */
    slots?: Array<string> | null;
    /**
     * Timezone
     */
    timezone?: string | null;
};

/**
 * AccountPosting
 */
export type AccountPosting = {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Channels
     */
    channels?: Array<ChannelProgress>;
    /**
     * Days Left
     */
    days_left?: number;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Held
     */
    held?: number;
    /**
     * Last Sent At
     */
    last_sent_at?: string | null;
    /**
     * Next Slot
     */
    next_slot?: string | null;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Per Day
     */
    per_day?: number;
    /**
     * Posted Total
     */
    posted_total?: number;
    /**
     * State
     */
    state?: 'off' | 'problem' | 'paused' | 'waiting' | 'on' | 'outage';
    /**
     * Timezone
     */
    timezone?: string;
    /**
     * Unanswered
     */
    unanswered?: number;
    /**
     * Waiting
     */
    waiting?: number;
};

/**
 * BackfillReport
 *
 * Result of `jobs backfill`.
 */
export type BackfillReport = {
    /**
     * Dry Run
     */
    dry_run: boolean;
    /**
     * Failed
     */
    failed?: Array<string>;
    /**
     * From Dict
     */
    from_dict?: number;
    /**
     * From Metadata
     */
    from_metadata?: number;
    /**
     * Written
     */
    written?: number;
};

/**
 * BrandKit
 */
export type BrandKit = {
    /**
     * Bio Link
     */
    bio_link?: string | null;
    /**
     * Caption Preset
     */
    caption_preset?: string;
    /**
     * Cta
     */
    cta?: string | null;
};

/**
 * CampaignRules
 */
export type CampaignRules = {
    /**
     * Deadline
     */
    deadline?: string | null;
    /**
     * Rate Per 1K
     */
    rate_per_1k?: number | null;
    /**
     * Required Links
     */
    required_links?: Array<string>;
    /**
     * Required Tags
     */
    required_tags?: Array<string>;
    /**
     * Rules
     */
    rules?: string;
    /**
     * Sponsored
     */
    sponsored?: boolean;
    /**
     * Submission Url
     */
    submission_url?: string | null;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * ChannelProgress
 */
export type ChannelProgress = {
    /**
     * Counts
     */
    counts?: {
        [key in PostStatus]?: number;
    };
    /**
     * Episodes Clipped
     */
    episodes_clipped?: number;
    /**
     * Episodes Clipping
     */
    episodes_clipping?: number;
    /**
     * Episodes Failed
     */
    episodes_failed?: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ChannelRef
 *
 * The channel a job's video came from; jobs with one are queued for posting (ADR-23).
 */
export type ChannelRef = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ClipOptions
 */
export type ClipOptions = {
    /**
     * Caption Style
     */
    caption_style?: 'default';
    /**
     * Language
     */
    language?: string | null;
    /**
     * Max Len
     */
    max_len?: number;
    /**
     * Min Len
     */
    min_len?: number;
    /**
     * Min Score
     */
    min_score?: number;
    /**
     * N
     */
    n?: number | null;
    /**
     * Reframe
     */
    reframe?: 'auto' | 'center' | 'blur';
};

/**
 * ClipState
 *
 * Working state of one clip (`job:<id>:clip:<clip_id>`), written only by its clip step.
 */
export type ClipState = {
    /**
     * Clip Id
     */
    clip_id: string;
    /**
     * Cost
     */
    cost?: Array<StageCost>;
    error?: JobError | null;
    progress?: Progress | null;
    /**
     * Result Ref
     */
    result_ref?: string | null;
    /**
     * Spec Ref
     */
    spec_ref: string;
    status?: ClipStatus;
    /**
     * Telegram Sent
     */
    telegram_sent?: boolean;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ClipStatus
 */
export type ClipStatus = 'pending' | 'running' | 'done' | 'failed';

/**
 * CostSummary
 */
export type CostSummary = {
    /**
     * Stages
     */
    stages?: Array<StageCost>;
    /**
     * Total Usd
     */
    readonly total_usd: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImportReport
 *
 * Result of `posting import` (Dict queue -> Postgres, spec §5.5).
 */
export type ImportReport = {
    /**
     * Already
     */
    already?: number;
    /**
     * By Status
     */
    by_status?: {
        [key in PostStatus]?: number;
    };
    /**
     * Dict Items
     */
    dict_items?: number;
    /**
     * Dry Run
     */
    dry_run: boolean;
    /**
     * Failed
     */
    failed?: Array<string>;
    /**
     * From Snapshot
     */
    from_snapshot?: number;
    /**
     * Imported
     */
    imported?: number;
    /**
     * Missing Source
     */
    missing_source?: Array<string>;
    /**
     * Paused
     */
    paused?: boolean;
};

/**
 * JobError
 */
export type JobError = {
    /**
     * Error Type
     */
    error_type: string;
    /**
     * Message
     */
    message: string;
    stage: StageName;
};

/**
 * JobInput
 */
export type JobInput = {
    channel?: ChannelRef | null;
    notify?: TelegramTarget | null;
    options?: ClipOptions;
    permission: Permission;
    /**
     * Source Credit
     */
    source_credit?: string | null;
    /**
     * Source Label
     */
    source_label?: string | null;
    /**
     * Source Path
     */
    source_path?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Telegram File Id
     */
    telegram_file_id?: string | null;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'done' | 'failed';

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export type JobView = {
    /**
     * Clips
     */
    clips: Array<ClipState>;
    cost: CostSummary;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Download Url
     */
    download_url?: string | null;
    error?: JobError | null;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Output Zip
     */
    output_zip?: string | null;
    progress?: Progress | null;
    stage: StageName | null;
    status: JobStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * Permission
 *
 * Permission basis for using a source (docs/SOURCING.md).
 */
export type Permission = 'own' | 'creator_agreement' | 'clipping_program' | 'cc_by' | 'public_domain';

/**
 * Platform
 */
export type Platform = 'tiktok' | 'instagram' | 'youtube' | 'facebook';

/**
 * PlatformProfile
 */
export type PlatformProfile = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Handle
     */
    handle?: string | null;
    /**
     * Hashtags
     */
    hashtags?: Array<string>;
    /**
     * Max Len
     */
    max_len?: number | null;
    /**
     * Min Len
     */
    min_len?: number | null;
};

/**
 * PostStatus
 *
 * Derived from a clip's keys, never stored (spec §4).
 */
export type PostStatus = 'queued' | 'sent' | 'partly_posted' | 'posted' | 'skipped' | 'rejected' | 'unavailable';

/**
 * PostingOverview
 *
 * What `/status`, `GET /posting` and `clipforge status` show (spec §9).
 */
export type PostingOverview = {
    /**
     * Accounts
     */
    accounts?: Array<AccountPosting>;
    /**
     * Channels
     */
    channels: Array<ChannelProgress>;
    /**
     * Days Left
     */
    days_left: number;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Next Slot
     */
    next_slot: string | null;
    /**
     * Outage Since
     */
    outage_since?: string | null;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Per Day
     */
    per_day: number;
    /**
     * Posted Total
     */
    posted_total?: number;
    /**
     * Problem
     */
    problem?: string | null;
    /**
     * State
     */
    state?: 'off' | 'problem' | 'paused' | 'waiting' | 'on' | 'outage';
    /**
     * Waiting
     */
    waiting: number;
};

/**
 * PostingSchedule
 */
export type PostingSchedule = {
    /**
     * Chat Id
     */
    chat_id?: number | null;
    /**
     * Hashtags
     */
    hashtags?: Array<string>;
    /**
     * Slots
     */
    slots?: Array<string>;
    /**
     * Timezone
     */
    timezone?: string;
};

/**
 * Progress
 */
export type Progress = {
    /**
     * At
     */
    at: string;
    /**
     * Message
     */
    message?: string;
    /**
     * Pct
     */
    pct: number;
    stage: StageName;
};

/**
 * PublisherProfile
 */
export type PublisherProfile = {
    /**
     * Disconnected
     */
    disconnected?: {
        [key in Platform]?: string;
    };
    /**
     * Facebook Page Id
     */
    facebook_page_id?: string | null;
    /**
     * Profile
     */
    profile: string;
};

/**
 * Source
 */
export type Source = {
    /**
     * Account Id
     */
    account_id: string;
    campaign?: CampaignRules | null;
    /**
     * Creator Handles
     */
    creator_handles?: {
        [key in Platform]?: string;
    };
    /**
     * Credit Name
     */
    credit_name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind?: 'channel' | 'campaign' | 'own';
    /**
     * Notes
     */
    notes?: string;
    permission: SourcePermission;
    /**
     * Status
     */
    status?: 'active' | 'paused' | 'ended';
    /**
     * Url
     */
    url?: string | null;
};

/**
 * SourceEvent
 *
 * One change to a source (source_events): who, when, before and after.
 */
export type SourceEvent = {
    /**
     * Action
     */
    action: 'created' | 'updated' | 'imported';
    /**
     * Actor
     */
    actor: string;
    /**
     * After
     */
    after: {
        [key: string]: unknown;
    };
    /**
     * At
     */
    at: string;
    /**
     * Before
     */
    before?: {
        [key: string]: unknown;
    } | null;
    /**
     * Source Id
     */
    source_id: string;
};

/**
 * SourcePermission
 *
 * The legal basis for posting a source's content (a business record, not config).
 */
export type SourcePermission = {
    /**
     * Evidence Url
     */
    evidence_url?: string | null;
    /**
     * Expires At
     */
    expires_at?: string | null;
    /**
     * Granted At
     */
    granted_at?: string | null;
    /**
     * Granted By
     */
    granted_by?: string | null;
    /**
     * Monetization Allowed
     */
    monetization_allowed?: boolean | null;
    /**
     * Platforms
     */
    platforms?: Array<Platform>;
    /**
     * Restrictions
     */
    restrictions?: string;
    /**
     * Translation Allowed
     */
    translation_allowed?: boolean | null;
    type: Permission;
};

/**
 * StageCost
 */
export type StageCost = {
    /**
     * Cached
     */
    cached?: boolean;
    /**
     * Clip Id
     */
    clip_id?: string | null;
    /**
     * Gpu S
     */
    gpu_s?: number;
    /**
     * Gpu Type
     */
    gpu_type?: string | null;
    /**
     * Llm Calls
     */
    llm_calls?: number;
    /**
     * Llm Input Tokens
     */
    llm_input_tokens?: number;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Output Tokens
     */
    llm_output_tokens?: number;
    stage: StageName;
    /**
     * Usd Estimate
     */
    usd_estimate?: number;
    /**
     * Wall S
     */
    wall_s?: number;
};

/**
 * StageName
 */
export type StageName = 'ingest' | 'transcribe' | 'highlights' | 'reframe' | 'captions' | 'render' | 'package';

/**
 * Submission
 *
 * A campaign clip's post, to paste into the campaign's form (spec §6.3).
 */
export type Submission = {
    /**
     * Item Id
     */
    item_id: string;
    platform: Platform;
    /**
     * Posted At
     */
    posted_at: string;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * TelegramTarget
 *
 * Where the Telegram notifier reports a job (the chat that sent it).
 */
export type TelegramTarget = {
    /**
     * Chat Id
     */
    chat_id: number;
    /**
     * Reply To Message Id
     */
    reply_to_message_id?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VerifyReport
 *
 * Dict versus Postgres for one account.
 */
export type VerifyReport = {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Dict Items
     */
    dict_items?: number;
    /**
     * Differences
     */
    differences?: number;
    /**
     * First
     */
    first?: Array<string>;
    /**
     * Postgres Items
     */
    postgres_items?: number;
};

/**
 * CostSummary
 */
export type CostSummaryWritable = {
    /**
     * Stages
     */
    stages?: Array<StageCost>;
};

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export type JobViewWritable = {
    /**
     * Clips
     */
    clips: Array<ClipState>;
    cost: CostSummaryWritable;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Download Url
     */
    download_url?: string | null;
    error?: JobError | null;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Output Zip
     */
    output_zip?: string | null;
    progress?: Progress | null;
    stage: StageName | null;
    status: JobStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

export type GetAccountsAccountsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/accounts';
};

export type GetAccountsAccountsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccountsAccountsGetError = GetAccountsAccountsGetErrors[keyof GetAccountsAccountsGetErrors];

export type GetAccountsAccountsGetResponses = {
    /**
     * Response Get Accounts Accounts Get
     *
     * Successful Response
     */
    200: Array<Account>;
};

export type GetAccountsAccountsGetResponse = GetAccountsAccountsGetResponses[keyof GetAccountsAccountsGetResponses];

export type PostAccountAccountsPostData = {
    body: AccountCreate;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/accounts';
};

export type PostAccountAccountsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAccountAccountsPostError = PostAccountAccountsPostErrors[keyof PostAccountAccountsPostErrors];

export type PostAccountAccountsPostResponses = {
    /**
     * Successful Response
     */
    201: Account;
};

export type PostAccountAccountsPostResponse = PostAccountAccountsPostResponses[keyof PostAccountAccountsPostResponses];

export type GetAccountAccountsAccountIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type GetAccountAccountsAccountIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAccountAccountsAccountIdGetError = GetAccountAccountsAccountIdGetErrors[keyof GetAccountAccountsAccountIdGetErrors];

export type GetAccountAccountsAccountIdGetResponses = {
    /**
     * Successful Response
     */
    200: Account;
};

export type GetAccountAccountsAccountIdGetResponse = GetAccountAccountsAccountIdGetResponses[keyof GetAccountAccountsAccountIdGetResponses];

export type PatchAccountAccountsAccountIdPatchData = {
    body: AccountEdit;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Account Id
         */
        account_id: string;
    };
    query?: never;
    url: '/accounts/{account_id}';
};

export type PatchAccountAccountsAccountIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchAccountAccountsAccountIdPatchError = PatchAccountAccountsAccountIdPatchErrors[keyof PatchAccountAccountsAccountIdPatchErrors];

export type PatchAccountAccountsAccountIdPatchResponses = {
    /**
     * Successful Response
     */
    200: Account;
};

export type PatchAccountAccountsAccountIdPatchResponse = PatchAccountAccountsAccountIdPatchResponses[keyof PatchAccountAccountsAccountIdPatchResponses];

export type PostJobJobsPostData = {
    body: JobInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/jobs';
};

export type PostJobJobsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostJobJobsPostError = PostJobJobsPostErrors[keyof PostJobJobsPostErrors];

export type PostJobJobsPostResponses = {
    /**
     * Response Post Job Jobs Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type PostJobJobsPostResponse = PostJobJobsPostResponses[keyof PostJobJobsPostResponses];

export type PostJobsBackfillJobsBackfillPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Dry Run
         */
        dry_run?: boolean;
    };
    url: '/jobs/backfill';
};

export type PostJobsBackfillJobsBackfillPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostJobsBackfillJobsBackfillPostError = PostJobsBackfillJobsBackfillPostErrors[keyof PostJobsBackfillJobsBackfillPostErrors];

export type PostJobsBackfillJobsBackfillPostResponses = {
    /**
     * Successful Response
     */
    200: BackfillReport;
};

export type PostJobsBackfillJobsBackfillPostResponse = PostJobsBackfillJobsBackfillPostResponses[keyof PostJobsBackfillJobsBackfillPostResponses];

export type GetJobJobsJobIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobJobsJobIdGetError = GetJobJobsJobIdGetErrors[keyof GetJobJobsJobIdGetErrors];

export type GetJobJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type GetJobJobsJobIdGetResponse = GetJobJobsJobIdGetResponses[keyof GetJobJobsJobIdGetResponses];

export type DownloadJobsJobIdDownloadGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query: {
        /**
         * Exp
         */
        exp: number;
        /**
         * Sig
         */
        sig: string;
    };
    url: '/jobs/{job_id}/download';
};

export type DownloadJobsJobIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadJobsJobIdDownloadGetError = DownloadJobsJobIdDownloadGetErrors[keyof DownloadJobsJobIdDownloadGetErrors];

export type DownloadJobsJobIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostResumeJobsJobIdResumePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/resume';
};

export type PostResumeJobsJobIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostResumeJobsJobIdResumePostError = PostResumeJobsJobIdResumePostErrors[keyof PostResumeJobsJobIdResumePostErrors];

export type PostResumeJobsJobIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type PostResumeJobsJobIdResumePostResponse = PostResumeJobsJobIdResumePostResponses[keyof PostResumeJobsJobIdResumePostResponses];

export type GetPostingPostingGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/posting';
};

export type GetPostingPostingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostingPostingGetError = GetPostingPostingGetErrors[keyof GetPostingPostingGetErrors];

export type GetPostingPostingGetResponses = {
    /**
     * Successful Response
     */
    200: PostingOverview;
};

export type GetPostingPostingGetResponse = GetPostingPostingGetResponses[keyof GetPostingPostingGetResponses];

export type PostPostingImportPostingImportPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Dry Run
         */
        dry_run?: boolean;
    };
    url: '/posting/import';
};

export type PostPostingImportPostingImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPostingImportPostingImportPostError = PostPostingImportPostingImportPostErrors[keyof PostPostingImportPostingImportPostErrors];

export type PostPostingImportPostingImportPostResponses = {
    /**
     * Successful Response
     */
    200: ImportReport;
};

export type PostPostingImportPostingImportPostResponse = PostPostingImportPostingImportPostResponses[keyof PostPostingImportPostingImportPostResponses];

export type PostPostingRebuildPostingRebuildPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/posting/rebuild';
};

export type PostPostingRebuildPostingRebuildPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPostingRebuildPostingRebuildPostError = PostPostingRebuildPostingRebuildPostErrors[keyof PostPostingRebuildPostingRebuildPostErrors];

export type PostPostingRebuildPostingRebuildPostResponses = {
    /**
     * Response Post Posting Rebuild Posting Rebuild Post
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type PostPostingRebuildPostingRebuildPostResponse = PostPostingRebuildPostingRebuildPostResponses[keyof PostPostingRebuildPostingRebuildPostResponses];

export type PostPostingRestorePostingRestorePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Date
         */
        date?: string | null;
    };
    url: '/posting/restore';
};

export type PostPostingRestorePostingRestorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPostingRestorePostingRestorePostError = PostPostingRestorePostingRestorePostErrors[keyof PostPostingRestorePostingRestorePostErrors];

export type PostPostingRestorePostingRestorePostResponses = {
    /**
     * Response Post Posting Restore Posting Restore Post
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type PostPostingRestorePostingRestorePostResponse = PostPostingRestorePostingRestorePostResponses[keyof PostPostingRestorePostingRestorePostResponses];

export type GetPostingVerifyPostingVerifyGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/posting/verify';
};

export type GetPostingVerifyPostingVerifyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostingVerifyPostingVerifyGetError = GetPostingVerifyPostingVerifyGetErrors[keyof GetPostingVerifyPostingVerifyGetErrors];

export type GetPostingVerifyPostingVerifyGetResponses = {
    /**
     * Successful Response
     */
    200: VerifyReport;
};

export type GetPostingVerifyPostingVerifyGetResponse = GetPostingVerifyPostingVerifyGetResponses[keyof GetPostingVerifyPostingVerifyGetResponses];

export type GetSourcesSourcesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/sources';
};

export type GetSourcesSourcesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourcesSourcesGetError = GetSourcesSourcesGetErrors[keyof GetSourcesSourcesGetErrors];

export type GetSourcesSourcesGetResponses = {
    /**
     * Response Get Sources Sources Get
     *
     * Successful Response
     */
    200: Array<Source>;
};

export type GetSourcesSourcesGetResponse = GetSourcesSourcesGetResponses[keyof GetSourcesSourcesGetResponses];

export type PostSourceSourcesPostData = {
    body: Source;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Clipforge-Actor
         */
        'x-clipforge-actor'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Action
         */
        action?: 'created' | 'imported';
    };
    url: '/sources';
};

export type PostSourceSourcesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostSourceSourcesPostError = PostSourceSourcesPostErrors[keyof PostSourceSourcesPostErrors];

export type PostSourceSourcesPostResponses = {
    /**
     * Successful Response
     */
    201: Source;
};

export type PostSourceSourcesPostResponse = PostSourceSourcesPostResponses[keyof PostSourceSourcesPostResponses];

export type GetSourceSourcesSourceIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}';
};

export type GetSourceSourcesSourceIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceSourcesSourceIdGetError = GetSourceSourcesSourceIdGetErrors[keyof GetSourceSourcesSourceIdGetErrors];

export type GetSourceSourcesSourceIdGetResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type GetSourceSourcesSourceIdGetResponse = GetSourceSourcesSourceIdGetResponses[keyof GetSourceSourcesSourceIdGetResponses];

export type PutSourceSourcesSourceIdPutData = {
    body: Source;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
        /**
         * X-Clipforge-Actor
         */
        'x-clipforge-actor'?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}';
};

export type PutSourceSourcesSourceIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutSourceSourcesSourceIdPutError = PutSourceSourcesSourceIdPutErrors[keyof PutSourceSourcesSourceIdPutErrors];

export type PutSourceSourcesSourceIdPutResponses = {
    /**
     * Successful Response
     */
    200: Source;
};

export type PutSourceSourcesSourceIdPutResponse = PutSourceSourcesSourceIdPutResponses[keyof PutSourceSourcesSourceIdPutResponses];

export type GetSourceEventsSourcesSourceIdEventsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}/events';
};

export type GetSourceEventsSourcesSourceIdEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSourceEventsSourcesSourceIdEventsGetError = GetSourceEventsSourcesSourceIdEventsGetErrors[keyof GetSourceEventsSourcesSourceIdEventsGetErrors];

export type GetSourceEventsSourcesSourceIdEventsGetResponses = {
    /**
     * Response Get Source Events Sources  Source Id  Events Get
     *
     * Successful Response
     */
    200: Array<SourceEvent>;
};

export type GetSourceEventsSourcesSourceIdEventsGetResponse = GetSourceEventsSourcesSourceIdEventsGetResponses[keyof GetSourceEventsSourcesSourceIdEventsGetResponses];

export type GetSubmissionsSourcesSourceIdSubmissionsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Source Id
         */
        source_id: string;
    };
    query?: never;
    url: '/sources/{source_id}/submissions';
};

export type GetSubmissionsSourcesSourceIdSubmissionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubmissionsSourcesSourceIdSubmissionsGetError = GetSubmissionsSourcesSourceIdSubmissionsGetErrors[keyof GetSubmissionsSourcesSourceIdSubmissionsGetErrors];

export type GetSubmissionsSourcesSourceIdSubmissionsGetResponses = {
    /**
     * Response Get Submissions Sources  Source Id  Submissions Get
     *
     * Successful Response
     */
    200: Array<Submission>;
};

export type GetSubmissionsSourcesSourceIdSubmissionsGetResponse = GetSubmissionsSourcesSourceIdSubmissionsGetResponses[keyof GetSubmissionsSourcesSourceIdSubmissionsGetResponses];

export type TelegramWebhookTelegramWebhookPostData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    headers?: {
        /**
         * X-Telegram-Bot-Api-Secret-Token
         */
        'x-telegram-bot-api-secret-token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/telegram/webhook';
};

export type TelegramWebhookTelegramWebhookPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelegramWebhookTelegramWebhookPostError = TelegramWebhookTelegramWebhookPostErrors[keyof TelegramWebhookTelegramWebhookPostErrors];

export type TelegramWebhookTelegramWebhookPostResponses = {
    /**
     * Response Telegram Webhook Telegram Webhook Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type TelegramWebhookTelegramWebhookPostResponse = TelegramWebhookTelegramWebhookPostResponses[keyof TelegramWebhookTelegramWebhookPostResponses];
