// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountPosting
 */
export type AccountPosting = {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Channels
     */
    channels?: Array<ChannelProgress>;
    /**
     * Days Left
     */
    days_left?: number;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Held
     */
    held?: number;
    /**
     * Next Slot
     */
    next_slot?: string | null;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Per Day
     */
    per_day?: number;
    /**
     * Waiting
     */
    waiting?: number;
};

/**
 * ChannelProgress
 */
export type ChannelProgress = {
    /**
     * Counts
     */
    counts?: {
        [key in PostStatus]?: number;
    };
    /**
     * Episodes Clipped
     */
    episodes_clipped?: number;
    /**
     * Episodes Clipping
     */
    episodes_clipping?: number;
    /**
     * Episodes Failed
     */
    episodes_failed?: number;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ChannelRef
 *
 * The channel a job's video came from; jobs with one are queued for posting (ADR-23).
 */
export type ChannelRef = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
};

/**
 * ClipOptions
 */
export type ClipOptions = {
    /**
     * Caption Style
     */
    caption_style?: 'default';
    /**
     * Language
     */
    language?: string | null;
    /**
     * Max Len
     */
    max_len?: number;
    /**
     * Min Len
     */
    min_len?: number;
    /**
     * Min Score
     */
    min_score?: number;
    /**
     * N
     */
    n?: number | null;
    /**
     * Reframe
     */
    reframe?: 'auto' | 'center' | 'blur';
};

/**
 * ClipState
 *
 * Working state of one clip (`job:<id>:clip:<clip_id>`), written only by its clip step.
 */
export type ClipState = {
    /**
     * Clip Id
     */
    clip_id: string;
    /**
     * Cost
     */
    cost?: Array<StageCost>;
    error?: JobError | null;
    progress?: Progress | null;
    /**
     * Result Ref
     */
    result_ref?: string | null;
    /**
     * Spec Ref
     */
    spec_ref: string;
    status?: ClipStatus;
    /**
     * Telegram Sent
     */
    telegram_sent?: boolean;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ClipStatus
 */
export type ClipStatus = 'pending' | 'running' | 'done' | 'failed';

/**
 * CostSummary
 */
export type CostSummary = {
    /**
     * Stages
     */
    stages?: Array<StageCost>;
    /**
     * Total Usd
     */
    readonly total_usd: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobError
 */
export type JobError = {
    /**
     * Error Type
     */
    error_type: string;
    /**
     * Message
     */
    message: string;
    stage: StageName;
};

/**
 * JobInput
 */
export type JobInput = {
    channel?: ChannelRef | null;
    notify?: TelegramTarget | null;
    options?: ClipOptions;
    permission: Permission;
    /**
     * Source Credit
     */
    source_credit?: string | null;
    /**
     * Source Label
     */
    source_label?: string | null;
    /**
     * Source Path
     */
    source_path?: string | null;
    /**
     * Source Url
     */
    source_url?: string | null;
    /**
     * Telegram File Id
     */
    telegram_file_id?: string | null;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'done' | 'failed';

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export type JobView = {
    /**
     * Clips
     */
    clips: Array<ClipState>;
    cost: CostSummary;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Download Url
     */
    download_url?: string | null;
    error?: JobError | null;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Output Zip
     */
    output_zip?: string | null;
    progress?: Progress | null;
    stage: StageName | null;
    status: JobStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * Permission
 *
 * Permission basis for using a source (docs/SOURCING.md).
 */
export type Permission = 'own' | 'creator_agreement' | 'clipping_program' | 'cc_by' | 'public_domain';

/**
 * PostStatus
 *
 * Derived from a clip's keys, never stored (spec §4).
 */
export type PostStatus = 'queued' | 'sent' | 'partly_posted' | 'posted' | 'skipped' | 'rejected' | 'unavailable';

/**
 * PostingOverview
 *
 * What `/status`, `GET /posting` and `clipforge status` show (spec §9).
 */
export type PostingOverview = {
    /**
     * Accounts
     */
    accounts?: Array<AccountPosting>;
    /**
     * Channels
     */
    channels: Array<ChannelProgress>;
    /**
     * Days Left
     */
    days_left: number;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Next Slot
     */
    next_slot: string | null;
    /**
     * Paused
     */
    paused: boolean;
    /**
     * Per Day
     */
    per_day: number;
    /**
     * Problem
     */
    problem?: string | null;
    /**
     * Waiting
     */
    waiting: number;
};

/**
 * Progress
 */
export type Progress = {
    /**
     * At
     */
    at: string;
    /**
     * Message
     */
    message?: string;
    /**
     * Pct
     */
    pct: number;
    stage: StageName;
};

/**
 * StageCost
 */
export type StageCost = {
    /**
     * Cached
     */
    cached?: boolean;
    /**
     * Clip Id
     */
    clip_id?: string | null;
    /**
     * Gpu S
     */
    gpu_s?: number;
    /**
     * Gpu Type
     */
    gpu_type?: string | null;
    /**
     * Llm Calls
     */
    llm_calls?: number;
    /**
     * Llm Input Tokens
     */
    llm_input_tokens?: number;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Output Tokens
     */
    llm_output_tokens?: number;
    stage: StageName;
    /**
     * Usd Estimate
     */
    usd_estimate?: number;
    /**
     * Wall S
     */
    wall_s?: number;
};

/**
 * StageName
 */
export type StageName = 'ingest' | 'transcribe' | 'highlights' | 'reframe' | 'captions' | 'render' | 'package';

/**
 * TelegramTarget
 *
 * Where the Telegram notifier reports a job (the chat that sent it).
 */
export type TelegramTarget = {
    /**
     * Chat Id
     */
    chat_id: number;
    /**
     * Reply To Message Id
     */
    reply_to_message_id?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * CostSummary
 */
export type CostSummaryWritable = {
    /**
     * Stages
     */
    stages?: Array<StageCost>;
};

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export type JobViewWritable = {
    /**
     * Clips
     */
    clips: Array<ClipState>;
    cost: CostSummaryWritable;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Download Url
     */
    download_url?: string | null;
    error?: JobError | null;
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Output Zip
     */
    output_zip?: string | null;
    progress?: Progress | null;
    stage: StageName | null;
    status: JobStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

export type PostJobJobsPostData = {
    body: JobInput;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/jobs';
};

export type PostJobJobsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostJobJobsPostError = PostJobJobsPostErrors[keyof PostJobJobsPostErrors];

export type PostJobJobsPostResponses = {
    /**
     * Response Post Job Jobs Post
     *
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type PostJobJobsPostResponse = PostJobJobsPostResponses[keyof PostJobJobsPostResponses];

export type GetJobJobsJobIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobJobsJobIdGetError = GetJobJobsJobIdGetErrors[keyof GetJobJobsJobIdGetErrors];

export type GetJobJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type GetJobJobsJobIdGetResponse = GetJobJobsJobIdGetResponses[keyof GetJobJobsJobIdGetResponses];

export type DownloadJobsJobIdDownloadGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query: {
        /**
         * Exp
         */
        exp: number;
        /**
         * Sig
         */
        sig: string;
    };
    url: '/jobs/{job_id}/download';
};

export type DownloadJobsJobIdDownloadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadJobsJobIdDownloadGetError = DownloadJobsJobIdDownloadGetErrors[keyof DownloadJobsJobIdDownloadGetErrors];

export type DownloadJobsJobIdDownloadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PostResumeJobsJobIdResumePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/resume';
};

export type PostResumeJobsJobIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostResumeJobsJobIdResumePostError = PostResumeJobsJobIdResumePostErrors[keyof PostResumeJobsJobIdResumePostErrors];

export type PostResumeJobsJobIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: JobView;
};

export type PostResumeJobsJobIdResumePostResponse = PostResumeJobsJobIdResumePostResponses[keyof PostResumeJobsJobIdResumePostResponses];

export type GetPostingPostingGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/posting';
};

export type GetPostingPostingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostingPostingGetError = GetPostingPostingGetErrors[keyof GetPostingPostingGetErrors];

export type GetPostingPostingGetResponses = {
    /**
     * Successful Response
     */
    200: PostingOverview;
};

export type GetPostingPostingGetResponse = GetPostingPostingGetResponses[keyof GetPostingPostingGetResponses];

export type PostPostingRebuildPostingRebuildPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/posting/rebuild';
};

export type PostPostingRebuildPostingRebuildPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPostingRebuildPostingRebuildPostError = PostPostingRebuildPostingRebuildPostErrors[keyof PostPostingRebuildPostingRebuildPostErrors];

export type PostPostingRebuildPostingRebuildPostResponses = {
    /**
     * Response Post Posting Rebuild Posting Rebuild Post
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type PostPostingRebuildPostingRebuildPostResponse = PostPostingRebuildPostingRebuildPostResponses[keyof PostPostingRebuildPostingRebuildPostResponses];

export type PostPostingRestorePostingRestorePostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Date
         */
        date?: string | null;
    };
    url: '/posting/restore';
};

export type PostPostingRestorePostingRestorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPostingRestorePostingRestorePostError = PostPostingRestorePostingRestorePostErrors[keyof PostPostingRestorePostingRestorePostErrors];

export type PostPostingRestorePostingRestorePostResponses = {
    /**
     * Response Post Posting Restore Posting Restore Post
     *
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type PostPostingRestorePostingRestorePostResponse = PostPostingRestorePostingRestorePostResponses[keyof PostPostingRestorePostingRestorePostResponses];

export type TelegramWebhookTelegramWebhookPostData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    headers?: {
        /**
         * X-Telegram-Bot-Api-Secret-Token
         */
        'x-telegram-bot-api-secret-token'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/telegram/webhook';
};

export type TelegramWebhookTelegramWebhookPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelegramWebhookTelegramWebhookPostError = TelegramWebhookTelegramWebhookPostErrors[keyof TelegramWebhookTelegramWebhookPostErrors];

export type TelegramWebhookTelegramWebhookPostResponses = {
    /**
     * Response Telegram Webhook Telegram Webhook Post
     *
     * Successful Response
     */
    200: {
        [key: string]: boolean;
    };
};

export type TelegramWebhookTelegramWebhookPostResponse = TelegramWebhookTelegramWebhookPostResponses[keyof TelegramWebhookTelegramWebhookPostResponses];
