// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ChannelRef
 *
 * The channel a job's video came from; jobs with one are queued for posting (ADR-23).
 */
export const zChannelRef = z.object({
    name: z.string(),
    slug: z.string()
});

/**
 * ClipOptions
 */
export const zClipOptions = z.object({
    caption_style: z.literal('default').optional().default('default'),
    language: z.string().nullish(),
    max_len: z.number().lte(180).optional().default(60),
    min_len: z.number().gte(5).optional().default(30),
    min_score: z.number().gte(0).lte(1).optional().default(0.8),
    n: z.int().gte(1).lte(30).nullish(),
    reframe: z.enum([
        'auto',
        'center',
        'blur'
    ]).optional().default('auto')
});

/**
 * ClipStatus
 */
export const zClipStatus = z.enum([
    'pending',
    'running',
    'done',
    'failed'
]);

/**
 * JobStatus
 */
export const zJobStatus = z.enum([
    'queued',
    'running',
    'done',
    'failed'
]);

/**
 * Permission
 *
 * Permission basis for using a source (docs/SOURCING.md).
 */
export const zPermission = z.enum([
    'own',
    'creator_agreement',
    'clipping_program',
    'cc_by',
    'public_domain'
]);

/**
 * PostStatus
 *
 * Derived from a clip's keys, never stored (spec §4).
 */
export const zPostStatus = z.enum([
    'queued',
    'sent',
    'partly_posted',
    'posted',
    'skipped',
    'rejected',
    'unavailable'
]);

/**
 * ChannelProgress
 */
export const zChannelProgress = z.object({
    counts: z.record(z.string(), z.int()).optional(),
    episodes_clipped: z.int().optional().default(0),
    episodes_clipping: z.int().optional().default(0),
    episodes_failed: z.int().optional().default(0),
    name: z.string(),
    slug: z.string()
});

/**
 * AccountPosting
 */
export const zAccountPosting = z.object({
    account_id: z.string(),
    channels: z.array(zChannelProgress).optional(),
    days_left: z.int().optional().default(0),
    enabled: z.boolean(),
    held: z.int().optional().default(0),
    next_slot: z.iso.datetime({ offset: true, local: true }).nullish(),
    paused: z.boolean(),
    per_day: z.int().optional().default(0),
    waiting: z.int().optional().default(0)
});

/**
 * PostingOverview
 *
 * What `/status`, `GET /posting` and `clipforge status` show (spec §9).
 */
export const zPostingOverview = z.object({
    accounts: z.array(zAccountPosting).optional(),
    channels: z.array(zChannelProgress),
    days_left: z.int(),
    enabled: z.boolean(),
    next_slot: z.iso.datetime({ offset: true, local: true }).nullable(),
    paused: z.boolean(),
    per_day: z.int(),
    problem: z.string().nullish(),
    waiting: z.int()
});

/**
 * StageName
 */
export const zStageName = z.enum([
    'ingest',
    'transcribe',
    'highlights',
    'reframe',
    'captions',
    'render',
    'package'
]);

/**
 * JobError
 */
export const zJobError = z.object({
    error_type: z.string(),
    message: z.string(),
    stage: zStageName
});

/**
 * Progress
 */
export const zProgress = z.object({
    at: z.iso.datetime({ offset: true, local: true }),
    message: z.string().optional().default(''),
    pct: z.number().gte(0).lte(100),
    stage: zStageName
});

/**
 * StageCost
 */
export const zStageCost = z.object({
    cached: z.boolean().optional().default(false),
    clip_id: z.string().nullish(),
    gpu_s: z.number().optional().default(0),
    gpu_type: z.string().nullish(),
    llm_calls: z.int().optional().default(0),
    llm_input_tokens: z.int().optional().default(0),
    llm_model: z.string().nullish(),
    llm_output_tokens: z.int().optional().default(0),
    stage: zStageName,
    usd_estimate: z.number().optional().default(0),
    wall_s: z.number().optional().default(0)
});

/**
 * ClipState
 *
 * Working state of one clip (`job:<id>:clip:<clip_id>`), written only by its clip step.
 */
export const zClipState = z.object({
    clip_id: z.string(),
    cost: z.array(zStageCost).optional(),
    error: zJobError.nullish(),
    progress: zProgress.nullish(),
    result_ref: z.string().nullish(),
    spec_ref: z.string(),
    status: zClipStatus.optional().default('pending'),
    telegram_sent: z.boolean().optional().default(false),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

/**
 * CostSummary
 */
export const zCostSummary = z.object({
    stages: z.array(zStageCost).optional(),
    total_usd: z.number().readonly()
});

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export const zJobView = z.object({
    clips: z.array(zClipState),
    cost: zCostSummary,
    created_at: z.iso.datetime({ offset: true, local: true }),
    download_url: z.string().nullish(),
    error: zJobError.nullish(),
    job_id: z.string(),
    output_zip: z.string().nullish(),
    progress: zProgress.nullish(),
    stage: zStageName.nullable(),
    status: zJobStatus,
    updated_at: z.iso.datetime({ offset: true, local: true })
});

/**
 * TelegramTarget
 *
 * Where the Telegram notifier reports a job (the chat that sent it).
 */
export const zTelegramTarget = z.object({
    chat_id: z.int(),
    reply_to_message_id: z.int().nullish()
});

/**
 * JobInput
 */
export const zJobInput = z.object({
    channel: zChannelRef.nullish(),
    notify: zTelegramTarget.nullish(),
    options: zClipOptions.optional(),
    permission: zPermission,
    source_credit: z.string().nullish(),
    source_label: z.string().nullish(),
    source_path: z.string().nullish(),
    source_url: z.url().min(1).nullish(),
    telegram_file_id: z.string().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * CostSummary
 */
export const zCostSummaryWritable = z.object({
    stages: z.array(zStageCost).optional()
});

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export const zJobViewWritable = z.object({
    clips: z.array(zClipState),
    cost: zCostSummaryWritable,
    created_at: z.iso.datetime({ offset: true, local: true }),
    download_url: z.string().nullish(),
    error: zJobError.nullish(),
    job_id: z.string(),
    output_zip: z.string().nullish(),
    progress: zProgress.nullish(),
    stage: zStageName.nullable(),
    status: zJobStatus,
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zPostJobJobsPostBody = zJobInput;

export const zPostJobJobsPostHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Post Job Jobs Post
 *
 * Successful Response
 */
export const zPostJobJobsPostResponse = z.record(z.string(), z.string());

export const zGetJobJobsJobIdGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetJobJobsJobIdGetPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zGetJobJobsJobIdGetResponse = zJobView;

export const zDownloadJobsJobIdDownloadGetPath = z.object({
    job_id: z.string()
});

export const zDownloadJobsJobIdDownloadGetQuery = z.object({
    exp: z.int(),
    sig: z.string()
});

export const zPostResumeJobsJobIdResumePostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostResumeJobsJobIdResumePostPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zPostResumeJobsJobIdResumePostResponse = zJobView;

export const zGetPostingPostingGetHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetPostingPostingGetResponse = zPostingOverview;

export const zPostPostingRebuildPostingRebuildPostHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Post Posting Rebuild Posting Rebuild Post
 *
 * Successful Response
 */
export const zPostPostingRebuildPostingRebuildPostResponse = z.record(z.string(), z.int());

export const zPostPostingRestorePostingRestorePostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostPostingRestorePostingRestorePostQuery = z.object({
    date: z.string().nullish()
});

/**
 * Response Post Posting Restore Posting Restore Post
 *
 * Successful Response
 */
export const zPostPostingRestorePostingRestorePostResponse = z.record(z.string(), z.int());

/**
 * Body
 */
export const zTelegramWebhookTelegramWebhookPostBody = z.record(z.string(), z.unknown());

export const zTelegramWebhookTelegramWebhookPostHeaders = z.object({
    'x-telegram-bot-api-secret-token': z.string().nullish()
});

/**
 * Response Telegram Webhook Telegram Webhook Post
 *
 * Successful Response
 */
export const zTelegramWebhookTelegramWebhookPostResponse = z.record(z.string(), z.boolean());
