// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AccountCreate
 */
export const zAccountCreate = z.object({
    blueprint: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/),
    handle: z.string().regex(/^[A-Za-z0-9._]{1,30}$/),
    id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/).nullish(),
    language: z.enum(['en', 'es']),
    posting_from_env: z.boolean().optional().default(false)
});

/**
 * BackfillReport
 *
 * Result of `jobs backfill`.
 */
export const zBackfillReport = z.object({
    dry_run: z.boolean(),
    failed: z.array(z.string()).optional(),
    from_dict: z.int().optional().default(0),
    from_metadata: z.int().optional().default(0),
    written: z.int().optional().default(0)
});

/**
 * BrandKit
 */
export const zBrandKit = z.object({
    bio_link: z.string().nullish(),
    caption_preset: z.string().optional().default('default'),
    cta: z.string().nullish()
});

/**
 * CampaignRules
 */
export const zCampaignRules = z.object({
    deadline: z.iso.datetime({ offset: true, local: true }).nullish(),
    rate_per_1k: z.number().nullish(),
    required_links: z.array(z.url().min(1)).optional(),
    required_tags: z.array(z.string()).optional(),
    rules: z.string().optional().default(''),
    sponsored: z.boolean().optional().default(true),
    submission_url: z.url().min(1).nullish(),
    url: z.url().min(1).nullish()
});

/**
 * ChannelRef
 *
 * The channel a job's video came from; jobs with one are queued for posting (ADR-23).
 */
export const zChannelRef = z.object({
    name: z.string(),
    slug: z.string()
});

/**
 * ClipOptions
 */
export const zClipOptions = z.object({
    caption_style: z.literal('default').optional().default('default'),
    language: z.string().nullish(),
    max_len: z.number().lte(180).optional().default(60),
    min_len: z.number().gte(5).optional().default(30),
    min_score: z.number().gte(0).lte(1).optional().default(0.8),
    n: z.int().gte(1).lte(30).nullish(),
    reframe: z.enum([
        'auto',
        'center',
        'blur'
    ]).optional().default('auto')
});

/**
 * ClipStatus
 */
export const zClipStatus = z.enum([
    'pending',
    'running',
    'done',
    'failed'
]);

/**
 * JobStatus
 */
export const zJobStatus = z.enum([
    'queued',
    'running',
    'done',
    'failed'
]);

/**
 * Permission
 *
 * Permission basis for using a source (docs/SOURCING.md).
 */
export const zPermission = z.enum([
    'own',
    'creator_agreement',
    'clipping_program',
    'cc_by',
    'public_domain'
]);

/**
 * Platform
 */
export const zPlatform = z.enum([
    'tiktok',
    'instagram',
    'youtube',
    'facebook'
]);

/**
 * AccountEdit
 */
export const zAccountEdit = z.object({
    chat_id: z.int().nullish(),
    clear_chat: z.boolean().optional().default(false),
    handles: z.record(z.string(), z.string()).optional(),
    hashtags: z.array(z.string()).nullish(),
    review_tier: z.enum([
        'review',
        'sample',
        'auto'
    ]).nullish(),
    slots: z.array(z.string()).nullish(),
    timezone: z.string().nullish()
});

/**
 * PlatformProfile
 */
export const zPlatformProfile = z.object({
    enabled: z.boolean().optional().default(true),
    handle: z.string().regex(/^[A-Za-z0-9._]{1,30}$/).nullish(),
    hashtags: z.array(z.string()).optional(),
    max_len: z.number().nullish(),
    min_len: z.number().nullish()
});

/**
 * PostStatus
 *
 * Derived from a clip's keys, never stored (spec §4).
 */
export const zPostStatus = z.enum([
    'queued',
    'sent',
    'partly_posted',
    'posted',
    'skipped',
    'rejected',
    'unavailable'
]);

/**
 * ChannelProgress
 */
export const zChannelProgress = z.object({
    counts: z.record(z.string(), z.int()).optional(),
    episodes_clipped: z.int().optional().default(0),
    episodes_clipping: z.int().optional().default(0),
    episodes_failed: z.int().optional().default(0),
    name: z.string(),
    slug: z.string()
});

/**
 * AccountPosting
 */
export const zAccountPosting = z.object({
    account_id: z.string(),
    channels: z.array(zChannelProgress).optional(),
    days_left: z.int().optional().default(0),
    enabled: z.boolean(),
    held: z.int().optional().default(0),
    next_slot: z.iso.datetime({ offset: true, local: true }).nullish(),
    paused: z.boolean(),
    per_day: z.int().optional().default(0),
    timezone: z.string().optional().default('UTC'),
    waiting: z.int().optional().default(0)
});

/**
 * ImportReport
 *
 * Result of `posting import` (Dict queue -> Postgres, spec §5.5).
 */
export const zImportReport = z.object({
    already: z.int().optional().default(0),
    by_status: z.record(z.string(), z.int()).optional(),
    dict_items: z.int().optional().default(0),
    dry_run: z.boolean(),
    failed: z.array(z.string()).optional(),
    from_snapshot: z.int().optional().default(0),
    imported: z.int().optional().default(0),
    missing_source: z.array(z.string()).optional(),
    paused: z.boolean().optional().default(false)
});

/**
 * PostingOverview
 *
 * What `/status`, `GET /posting` and `clipforge status` show (spec §9).
 */
export const zPostingOverview = z.object({
    accounts: z.array(zAccountPosting).optional(),
    channels: z.array(zChannelProgress),
    days_left: z.int(),
    enabled: z.boolean(),
    next_slot: z.iso.datetime({ offset: true, local: true }).nullable(),
    paused: z.boolean(),
    per_day: z.int(),
    problem: z.string().nullish(),
    waiting: z.int()
});

/**
 * PostingSchedule
 */
export const zPostingSchedule = z.object({
    chat_id: z.int().nullish(),
    hashtags: z.array(z.string()).optional(),
    slots: z.array(z.string()).optional(),
    timezone: z.string().optional().default('America/New_York')
});

/**
 * Account
 */
export const zAccount = z.object({
    blueprint: z.string(),
    blueprint_version: z.int(),
    brand: zBrandKit.optional(),
    id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/),
    kind: z.enum([
        'clips',
        'story',
        'band',
        'avatar',
        'model'
    ]),
    language: z.enum(['en', 'es']),
    monthly_budget_usd: z.number().optional().default(0),
    niche: z.string(),
    paired_account_id: z.string().nullish(),
    persona_id: z.string().nullish(),
    platforms: z.record(z.string(), zPlatformProfile),
    posting: zPostingSchedule.optional(),
    review_tier: z.enum([
        'review',
        'sample',
        'auto'
    ]).optional().default('review')
});

/**
 * SourceEvent
 *
 * One change to a source (source_events): who, when, before and after.
 */
export const zSourceEvent = z.object({
    action: z.enum([
        'created',
        'updated',
        'imported'
    ]),
    actor: z.string(),
    after: z.record(z.string(), z.unknown()),
    at: z.iso.datetime({ offset: true, local: true }),
    before: z.record(z.string(), z.unknown()).nullish(),
    source_id: z.string()
});

/**
 * SourcePermission
 *
 * The legal basis for posting a source's content (a business record, not config).
 */
export const zSourcePermission = z.object({
    evidence_url: z.url().min(1).nullish(),
    expires_at: z.iso.datetime({ offset: true, local: true }).nullish(),
    granted_at: z.iso.date().nullish(),
    granted_by: z.string().nullish(),
    monetization_allowed: z.boolean().nullish(),
    platforms: z.array(zPlatform).min(1).optional(),
    restrictions: z.string().optional().default(''),
    translation_allowed: z.boolean().nullish(),
    type: zPermission
});

/**
 * Source
 */
export const zSource = z.object({
    account_id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/),
    campaign: zCampaignRules.nullish(),
    creator_handles: z.record(z.string(), z.string()).optional(),
    credit_name: z.string(),
    id: z.string().regex(/^[a-z0-9][a-z0-9-]{0,39}$/),
    kind: z.enum([
        'channel',
        'campaign',
        'own'
    ]).optional().default('channel'),
    notes: z.string().optional().default(''),
    permission: zSourcePermission,
    status: z.enum([
        'active',
        'paused',
        'ended'
    ]).optional().default('active'),
    url: z.url().min(1).nullish()
});

/**
 * StageName
 */
export const zStageName = z.enum([
    'ingest',
    'transcribe',
    'highlights',
    'reframe',
    'captions',
    'render',
    'package'
]);

/**
 * JobError
 */
export const zJobError = z.object({
    error_type: z.string(),
    message: z.string(),
    stage: zStageName
});

/**
 * Progress
 */
export const zProgress = z.object({
    at: z.iso.datetime({ offset: true, local: true }),
    message: z.string().optional().default(''),
    pct: z.number().gte(0).lte(100),
    stage: zStageName
});

/**
 * StageCost
 */
export const zStageCost = z.object({
    cached: z.boolean().optional().default(false),
    clip_id: z.string().nullish(),
    gpu_s: z.number().optional().default(0),
    gpu_type: z.string().nullish(),
    llm_calls: z.int().optional().default(0),
    llm_input_tokens: z.int().optional().default(0),
    llm_model: z.string().nullish(),
    llm_output_tokens: z.int().optional().default(0),
    stage: zStageName,
    usd_estimate: z.number().optional().default(0),
    wall_s: z.number().optional().default(0)
});

/**
 * ClipState
 *
 * Working state of one clip (`job:<id>:clip:<clip_id>`), written only by its clip step.
 */
export const zClipState = z.object({
    clip_id: z.string(),
    cost: z.array(zStageCost).optional(),
    error: zJobError.nullish(),
    progress: zProgress.nullish(),
    result_ref: z.string().nullish(),
    spec_ref: z.string(),
    status: zClipStatus.optional().default('pending'),
    telegram_sent: z.boolean().optional().default(false),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

/**
 * CostSummary
 */
export const zCostSummary = z.object({
    stages: z.array(zStageCost).optional(),
    total_usd: z.number().readonly()
});

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export const zJobView = z.object({
    clips: z.array(zClipState),
    cost: zCostSummary,
    created_at: z.iso.datetime({ offset: true, local: true }),
    download_url: z.string().nullish(),
    error: zJobError.nullish(),
    job_id: z.string(),
    output_zip: z.string().nullish(),
    progress: zProgress.nullish(),
    stage: zStageName.nullable(),
    status: zJobStatus,
    updated_at: z.iso.datetime({ offset: true, local: true })
});

/**
 * Submission
 *
 * A campaign clip's post, to paste into the campaign's form (spec §6.3).
 */
export const zSubmission = z.object({
    item_id: z.string(),
    platform: zPlatform,
    posted_at: z.iso.datetime({ offset: true, local: true }),
    url: z.string().nullish()
});

/**
 * TelegramTarget
 *
 * Where the Telegram notifier reports a job (the chat that sent it).
 */
export const zTelegramTarget = z.object({
    chat_id: z.int(),
    reply_to_message_id: z.int().nullish()
});

/**
 * JobInput
 */
export const zJobInput = z.object({
    channel: zChannelRef.nullish(),
    notify: zTelegramTarget.nullish(),
    options: zClipOptions.optional(),
    permission: zPermission,
    source_credit: z.string().nullish(),
    source_label: z.string().nullish(),
    source_path: z.string().nullish(),
    source_url: z.url().min(1).nullish(),
    telegram_file_id: z.string().nullish()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VerifyReport
 *
 * Dict versus Postgres for one account.
 */
export const zVerifyReport = z.object({
    account_id: z.string(),
    dict_items: z.int().optional().default(0),
    differences: z.int().optional().default(0),
    first: z.array(z.string()).optional(),
    postgres_items: z.int().optional().default(0)
});

/**
 * CostSummary
 */
export const zCostSummaryWritable = z.object({
    stages: z.array(zStageCost).optional()
});

/**
 * JobView
 *
 * What the API returns: the core record merged with its clips, and the total cost.
 */
export const zJobViewWritable = z.object({
    clips: z.array(zClipState),
    cost: zCostSummaryWritable,
    created_at: z.iso.datetime({ offset: true, local: true }),
    download_url: z.string().nullish(),
    error: zJobError.nullish(),
    job_id: z.string(),
    output_zip: z.string().nullish(),
    progress: zProgress.nullish(),
    stage: zStageName.nullable(),
    status: zJobStatus,
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zGetAccountsAccountsGetHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Get Accounts Accounts Get
 *
 * Successful Response
 */
export const zGetAccountsAccountsGetResponse = z.array(zAccount);

export const zPostAccountAccountsPostBody = zAccountCreate;

export const zPostAccountAccountsPostHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Successful Response
 */
export const zPostAccountAccountsPostResponse = zAccount;

export const zGetAccountAccountsAccountIdGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetAccountAccountsAccountIdGetPath = z.object({
    account_id: z.string()
});

/**
 * Successful Response
 */
export const zGetAccountAccountsAccountIdGetResponse = zAccount;

export const zPatchAccountAccountsAccountIdPatchBody = zAccountEdit;

export const zPatchAccountAccountsAccountIdPatchHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPatchAccountAccountsAccountIdPatchPath = z.object({
    account_id: z.string()
});

/**
 * Successful Response
 */
export const zPatchAccountAccountsAccountIdPatchResponse = zAccount;

export const zPostJobJobsPostBody = zJobInput;

export const zPostJobJobsPostHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Post Job Jobs Post
 *
 * Successful Response
 */
export const zPostJobJobsPostResponse = z.record(z.string(), z.string());

export const zPostJobsBackfillJobsBackfillPostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostJobsBackfillJobsBackfillPostQuery = z.object({
    dry_run: z.boolean().optional().default(false)
});

/**
 * Successful Response
 */
export const zPostJobsBackfillJobsBackfillPostResponse = zBackfillReport;

export const zGetJobJobsJobIdGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetJobJobsJobIdGetPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zGetJobJobsJobIdGetResponse = zJobView;

export const zDownloadJobsJobIdDownloadGetPath = z.object({
    job_id: z.string()
});

export const zDownloadJobsJobIdDownloadGetQuery = z.object({
    exp: z.int(),
    sig: z.string()
});

export const zPostResumeJobsJobIdResumePostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostResumeJobsJobIdResumePostPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zPostResumeJobsJobIdResumePostResponse = zJobView;

export const zGetPostingPostingGetHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetPostingPostingGetResponse = zPostingOverview;

export const zPostPostingImportPostingImportPostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostPostingImportPostingImportPostQuery = z.object({
    dry_run: z.boolean().optional().default(false)
});

/**
 * Successful Response
 */
export const zPostPostingImportPostingImportPostResponse = zImportReport;

export const zPostPostingRebuildPostingRebuildPostHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Post Posting Rebuild Posting Rebuild Post
 *
 * Successful Response
 */
export const zPostPostingRebuildPostingRebuildPostResponse = z.record(z.string(), z.int());

export const zPostPostingRestorePostingRestorePostHeaders = z.object({
    authorization: z.string().nullish()
});

export const zPostPostingRestorePostingRestorePostQuery = z.object({
    date: z.string().nullish()
});

/**
 * Response Post Posting Restore Posting Restore Post
 *
 * Successful Response
 */
export const zPostPostingRestorePostingRestorePostResponse = z.record(z.string(), z.int());

export const zGetPostingVerifyPostingVerifyGetHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Successful Response
 */
export const zGetPostingVerifyPostingVerifyGetResponse = zVerifyReport;

export const zGetSourcesSourcesGetHeaders = z.object({
    authorization: z.string().nullish()
});

/**
 * Response Get Sources Sources Get
 *
 * Successful Response
 */
export const zGetSourcesSourcesGetResponse = z.array(zSource);

export const zPostSourceSourcesPostBody = zSource;

export const zPostSourceSourcesPostHeaders = z.object({
    authorization: z.string().nullish(),
    'x-clipforge-actor': z.string().nullish()
});

export const zPostSourceSourcesPostQuery = z.object({
    action: z.enum(['created', 'imported']).optional().default('created')
});

/**
 * Successful Response
 */
export const zPostSourceSourcesPostResponse = zSource;

export const zGetSourceSourcesSourceIdGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetSourceSourcesSourceIdGetPath = z.object({
    source_id: z.string()
});

/**
 * Successful Response
 */
export const zGetSourceSourcesSourceIdGetResponse = zSource;

export const zPutSourceSourcesSourceIdPutBody = zSource;

export const zPutSourceSourcesSourceIdPutHeaders = z.object({
    authorization: z.string().nullish(),
    'x-clipforge-actor': z.string().nullish()
});

export const zPutSourceSourcesSourceIdPutPath = z.object({
    source_id: z.string()
});

/**
 * Successful Response
 */
export const zPutSourceSourcesSourceIdPutResponse = zSource;

export const zGetSourceEventsSourcesSourceIdEventsGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetSourceEventsSourcesSourceIdEventsGetPath = z.object({
    source_id: z.string()
});

/**
 * Response Get Source Events Sources  Source Id  Events Get
 *
 * Successful Response
 */
export const zGetSourceEventsSourcesSourceIdEventsGetResponse = z.array(zSourceEvent);

export const zGetSubmissionsSourcesSourceIdSubmissionsGetHeaders = z.object({
    authorization: z.string().nullish()
});

export const zGetSubmissionsSourcesSourceIdSubmissionsGetPath = z.object({
    source_id: z.string()
});

/**
 * Response Get Submissions Sources  Source Id  Submissions Get
 *
 * Successful Response
 */
export const zGetSubmissionsSourcesSourceIdSubmissionsGetResponse = z.array(zSubmission);

/**
 * Body
 */
export const zTelegramWebhookTelegramWebhookPostBody = z.record(z.string(), z.unknown());

export const zTelegramWebhookTelegramWebhookPostHeaders = z.object({
    'x-telegram-bot-api-secret-token': z.string().nullish()
});

/**
 * Response Telegram Webhook Telegram Webhook Post
 *
 * Successful Response
 */
export const zTelegramWebhookTelegramWebhookPostResponse = z.record(z.string(), z.boolean());
